//task 1
// var taskONE = document.getElementById("s1");
// console.log(taskONE.innerText);

//task 2
// var task2 = document.getElementById("myH1");
// task2.innerText = "my dom app";

//task 3
// var elementHello = document.getElementById("Hello");
// var elementBen = document.getElementById("Ben");
// var elementDance = document.getElementById("dance");
// var elementIsrael = document.getElementById("Israel");

// console.log(elementHello.innerText);
// console.log(elementBen.innerText);
// console.log(elementDance.innerText);
// console.log(elementIsrael.innerText);

//task 4
var myArray = document.getElementsByClassName("four");
function t4 (){
    for (var i = 0; i < myArray.length; i++){
        console.log(myArray[i])
    }    
}
t4();